export const tips = {
    simplex_seed: "Seed for the simplex noise generator. Altering the seed changes the pattern of the generated noise.",
    ridge_invert: "Inverts the height, making valleys appear as ridges and vice versa.",
    ridge_square: "Squares the height, giving a flatter appearance, with less dramatic peaks and hiding the folds.",
    layers_fundamental: "Base frequency for the first noise layer, controls the size of terrain features. Lower values creates broader, smoother terrain. Higher values will bring everything close together, resulting sharper terrain with steeper slopes.",
    layers_octaves: "Number of noise layers. More octaves will add details to the terrain.",
    layers_persistence: "Amount by which the height of each successive octave is decreased. Lower values makes each octave contribute less to the terrain.",
    layers_lacunarity: "Multiplier for the frequency of each successive octave. Higher values makes each octave pack more details, resulting in sharper terrain with steeper slopes.",
    continental_bass: "The lower part of the terrain.",
    continental_treble: "The higher part of the terrain, also acting as the selecting noise. When this noise is below the high threshold, the bass noise is added to the mix. When above the high threshold, only this treble noise is present.",
    continental_threshold: "Thresholds dictating which noise (bass or treble) will be used for the terrain height and how to mix them.",
    continental_low: "Low cutoff point. When the treble is below this value, the height is fully dictated by the bass.",
    continental_mid: "Controls the transition between bass and treble when treble is between the low and high thresholds. When lower, bass has a bigger influence. When higher, treble has a bigger influence.",
    continental_high: "High cutoff point. When the treble is above this value, the height is fully dictated by the treble.",
    terracing_steps: "Number of terraces used in the terrain. More terraces will create a smoother terrain.",
    noisy_terrace_min: "Minimum number of terraces used in the terrain. More terraces will create smoother terrain.",
    noisy_terrace_max: "Maximum number of terraces used in the terrain. More terraces will create smoother terrain.",
    noisy_terracer: "Noise dictating how much terraces will be used at a given point, normalized between min and max.",
    warping_frequency: "Scale factor for the warping coordinates, dictating how dense the warping is. Higher values will make the warping effect repeat more frequently, making the effect more visible.",
    warping_strength: "How much the warping effect distorts the coordinates. Higher value will make the terrain more swirly, making the effect more visible.",
    warper: "Noise dictating the magnitude of the warping effect.",
    tiling_coorscale: "Multiplier for the tile coordinates, dictates the tile density. Higher values will result in more tile packed into a chunk.",
    tiling_enabled: "Toggles tiling on or off.",
    tiling_noisescale: "Magnitude of the distortion applied to each tile. Higher values will make the tiles less square and more chaotic.",
}
