export const tips = {
    simplex: "Raw simplex noise, the foundamental terrain generation building block.\nCreates a landscape of smooth hills.",
    simplex_seed: "Seed for the simplex noise generator.\nAltering the seed changes the pattern of the generated noise.",
    ridge: "Simplex noise with a post-processing step to create a sharper terrain reminescent of a mountain chain.",
    ridge_invert: "Inverts the height, making valleys appear as ridges and vice versa.",
    ridge_square: "Squares the height, giving a flatter appearance, with less dramatic peaks and hiding the folds.",
    layered_simplex: "Multiple values (called octaves) of simplex noise layered on top of each other.\nCreates a more complex hilly terrain than plain simplex noise, with each octave adding more details.",
    layered_ridge: "Multiple values (called octaves) of simplex noise layered on top of each other.\nCreates a more complex mountaineous terrain than plain ridge noise, with each octave adding more details.",
    layers_fundamental: "Base frequency for the first noise layer, controls the size of terrain features.\nLower values creates broader, smoother terrain.\nHigher values will bring everything close together, resulting sharper terrain with steeper slopes.",
    layers_octaves: "Number of noise layers.\nMore octaves will add details to the terrain.",
    layers_persistence: "Amount by which the height of each successive octave is decreased.\nLower values makes each octave contribute less to the terrain.",
    layers_lacunarity: "Multiplier for the frequency of each successive octave.\nHigher values makes each octave pack more details, resulting in sharper terrain with steeper slopes.",
    continental_mix: "Layered simplex noise and layered ridge noise combined together.\nThe ridge part is what dictates the general shape of the terrain, whereas the simplex part influences the lower part of the terrain.\nThe result is a montaineous terrain with the lower elevations made of hills.",
    continental_bass: "The lower part of the terrain.",
    continental_treble: "The higher part of the terrain, also acting as the selecting noise.\nWhen this noise is below the high threshold, the bass noise is added to the mix.\nWhen above the high threshold, only this treble noise is present.",
    continental_threshold: "Thresholds dictating which noise (bass or treble) will be used for the terrain height and how to mix them.",
    continental_low: "Low cutoff point.\nWhen the treble is below this value, the height is fully dictated by the bass.",
    continental_mid: "Controls the transition between bass and treble when treble is between the low and high thresholds.\nWhen lower, bass has a bigger influence.\nWhen higher, treble has a bigger influence.",
    continental_high: "High cutoff point.\nWhen the treble is above this value, the height is fully dictated by the treble.",
    terracing: "Adds steps in the terrain, creating terraces.",
    terracing_constant: "Use the same amount of terraces everywhere.\nGenerates a blocky terrain with evenly-spaced terrain.",
    terracing_steps: "Number of terraces used in the terrain.\nMore terraces will create a smoother terrain.",
    terracing_noisy: "Use a different amount of terraces in different places.\nCreates a stepped and wobbly surface that increases in wobbleliness when the difference between the minimum and the maximum of terraces increases.",
    noisy_terrace_min: "Minimum number of terraces used in the terrain.\nMore terraces will create smoother terrain.",
    noisy_terrace_max: "Maximum number of terraces used in the terrain.\nMore terraces will create smoother terrain.",
    noisy_terracer: "Noise dictating how much terraces will be used at a given point, normalized between min and max.",
    warping: "Distorts the coordinates to hide straight lines in the terrain, introducing vortex-like perturbations.",
    warping_frequency: "Scale factor for the warping coordinates, dictating how dense the warping is.\nHigher values will make the warping effect repeat more frequently, making the effect more visible.",
    warping_strength: "How much the warping effect distorts the coordinates.\nHigher value will make the terrain more swirly, making the effect more visible.",
    warper: "Noise dictating the magnitude of the warping effect.",
    tiling: "Groups neighboring coordinates together to form chunks of uniform height.\nCan create shapes looking like continents.",
    tiling_coorscale: "Multiplier for the tile coordinates, dictates the tile density.\nHigher values will result in more tile packed into a chunk.",
    tiling_enabled: "Toggles tiling on or off.",
    tiling_noisescale: "Magnitude of the distortion applied to each tile.\nHigher values will make the tiles less square and more chaotic.",
}
